services:
  postgres:
    image: postgres:17-alpine
    container_name: premiere_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: premieredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - premiere_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  premiere_network:
    driver: bridge